# AEGIS — zokastech.fr — Apache 2.0 / MIT
{{- if and .Values.gateway.enabled (or .Values.gateway.secretEnv .Values.gateway.extraSecretData) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.fullname" . }}-gateway-env
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
type: Opaque
stringData:
  {{- range $k, $v := .Values.gateway.secretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- range $k, $v := .Values.gateway.extraSecretData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
