# AEGIS — zokastech.fr — Apache 2.0 / MIT
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis.fullname" . }}-redis
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      name: redis
  selector:
    {{- include "aegis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aegis.fullname" . }}-redis
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "aegis.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "aegis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "aegis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
        {{- if .Values.podSecurity.labelRestricted }}
        security.zokastech.fr/pod-standard: restricted
        {{- end }}
    spec:
      serviceAccountName: {{ include "aegis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          {{- if .Values.redis.auth.enabled }}
          args:
            - redis-server
            - --appendonly
            - "yes"
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aegis.fullname" . }}-redis
                  key: redis-password
          {{- else }}
          args:
            - redis-server
            - --appendonly
            - "yes"
          {{- end }}
          ports:
            - name: redis
              containerPort: 6379
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size | quote }}
  {{- end }}
{{- end }}
