# AEGIS — zokastech.fr — Apache 2.0 / MIT
{{- if and .Values.metrics.serviceMonitor.enabled .Values.gateway.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aegis.fullname" . }}-gateway
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "aegis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  endpoints:
    - port: http
      path: {{ .Values.metrics.serviceMonitor.path | quote }}
      interval: {{ .Values.metrics.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | quote }}
      scheme: {{ .Values.metrics.serviceMonitor.scheme | quote }}
      {{- if eq .Values.metrics.serviceMonitor.scheme "https" }}
      tlsConfig:
        insecureSkipVerify: {{ .Values.metrics.serviceMonitor.insecureSkipVerify }}
      {{- end }}
{{- end }}
